# -*- coding: utf-8 -*-
"""customer segmentation analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Se9F6rXx9jaoDllyTP4fXAggVxrje6ro
"""

!pip install pandas matplotlib seaborn scikit-learn

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv("/content/customer_segmentation.csv")

# Display first 5 rows
print(df.head())

# Check dataset info
print(df.info())

# Convert categorical columns into numerical values
le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df['Preferred_Category'] = le.fit_transform(df['Preferred_Category'])
df['City'] = le.fit_transform(df['City'])

# Select important features for clustering
X = df[['Annual_Income', 'Spending_Score']]

# Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Find optimal clusters using Elbow Method
wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

# Plot Elbow Graph
plt.figure(figsize=(8,5))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

# Apply KMeans Clustering
kmeans = KMeans(n_clusters=4, random_state=42)

df['Cluster'] = kmeans.fit_predict(X_scaled)

# Show clustered data
print(df.head())

# Visualization of clusters
plt.figure(figsize=(10,6))

sns.scatterplot(
    x=df['Annual_Income'],
    y=df['Spending_Score'],
    hue=df['Cluster'],
    palette='Set1',
    s=100
)

plt.title("Customer Segmentation")
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.show()

# Cluster Analysis
cluster_summary = df.groupby('Cluster').mean(numeric_only=True)

print("\nCluster Summary:")
print(cluster_summary)